//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMLbot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIMLbot.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The javascript tag is not implemented in this bot.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ). Please make sure that your aiml file end in a lowercase aiml extension, for example - myFile.aiml is valid but myFile.AIML is not..
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory specified as the path to the AIML files (.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) cannot be found by the AIMLLoader object. Please make sure the directory where you think the AIML files are to be found is the same as the directory specified in the settings file..
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An out of bounds index to topicstar was encountered when processing the input: .
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! Attempted (but failed) to &lt;learn&gt; some new AIML from the following URI: .
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An out of bounds index to thatstar was encountered when processing the input: .
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputStar out of bounds reference caused by input: .
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index set to non-integer value whilst processing star tag in response to the input: .
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A star tag tried to reference an empty InputStar collection when processing the input: .
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An input tag with a bady formed index (.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system tag is not implemented in this bot.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) was encountered processing the input: .
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An out of bounds index to thatstar was encountered when processing the input: .
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! A thatstar tag with a bady formed index (.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) was encountered processing the input: .
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An input tag with a bady formed index (.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) was encountered processing the input: .
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An out of bounds index to topicstar was encountered when processing the input: .
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! A thatstar tag with a bady formed index (.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) was encountered processing the input: .
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot could not find any response for the input: .
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOSSIP from user:.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with the path(s): .
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from the user with an id: .
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An input tag with a bady formed index (.
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) was encountered processing the input: .
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An input tag with a bady formed index (.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) was encountered processing the input: .
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An input tag with a bady formed index (.
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) was encountered processing the input: .
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An input tag with a bady formed index (.
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) was encountered processing the input: .
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , &apos;.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An input tag with a bady formed index (.
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) was encountered processing the input: .
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing AIML file: .
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! An input tag with a bady formed index (.
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) was encountered processing the input: .
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! Request timeout. User: .
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raw input: \&quot;.
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;.
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing pattern tag in a node found in.
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing template tag in the node with pattern:.
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found in.
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! Failed to load a new category into the graphmaster where the path =.
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and template =.
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to produced by a category in the file:.
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! Attempted to load a new category with an empty pattern where the path =.
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and template =.
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to produced by a category in the file:.
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! Request timeout. User:.
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raw input: \&quot;.
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot; processing template: \&quot;.
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to process AIML files found in the directory.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;.
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! A problem was encountered when trying to process the input: .
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with the template: \&quot;.
        /// </summary>
        internal static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;.
        /// </summary>
        internal static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished processing the AIML files..
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categories processed..
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any .aiml files in the specified directory (.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
    }
}
